export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  BEBOERE: '/beboere',
  GAMLE_BEBOERE: '/beboere/gamle',
  REGI: '/regi',
  TASKS: '/regi/oppgaver',
  REGISJEF: '/regisjef',
  REGIGODKJENNING: '/regisjef/godkjenning',
  REGILOGS: '/regisjef/logg',
  LEGG_TIL_BEBOER: '/romsjef/legg_til_beboer',
  HOME: '/',
  ADMIN: '/admin',
  PROFILE: '/profil',
  FORGOT_PASSWORD: '/glemt-passord',
  RESET_PASSWORD: '/reset-password',
};
