export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  REGI: '/regi',
  MY_REGI: '/regi/min-regi',
  TASKS: '/regi/oppgaver',
  REGISJEF: '/regisjef',
  REGIGODKJENNING_REVIEW: '/regisjef/godkjenning/:id',
  LEGG_TIL_BEBOER: '/romsjef/legg_til_beboer',
  IMPORTER_BRUKERE: '/romsjef/importer_brukere',
  HOME: '/',
  ADMIN: '/admin',
  ABOUTME: '/about_me',
  FORGOT_PASSWORD: '/glemt-passord',
  RESET_PASSWORD: '/reset-password',
};
