drop extension if exists "pg_net";

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'prisma') then
    create role prisma;
  end if;
end
$$;

create schema if not exists "dev";

create type "public"."work_type" as enum ('task', 'misc');


  create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
      );


alter table "public"."roles" enable row level security;


  create table "public"."users" (
    "name" text,
    "email" text,
    "birth_date" date,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean default false,
    "on_leave" boolean default true,
    "street" text,
    "postal_code" text,
    "city" text,
    "country" text,
    "phone" text,
    "profile_picture" text,
    "room_number" smallint,
    "seniority" smallint,
    "id" uuid not null,
    "role_id" bigint,
    "school_id" uuid,
    "study_id" uuid
      );


alter table "public"."users" enable row level security;


  create table "public"."work_assignments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "hours_used" real,
    "approved_state" smallint not null default '0'::smallint,
    "approval_comment" text,
    "approved_by_uuid" uuid,
    "user_uuid" uuid not null,
    "work_id" bigint not null
      );


alter table "public"."work_assignments" enable row level security;


  create table "public"."work_categories" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "description" text,
    "color" text,
    "is_active" boolean default true,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."work_categories" enable row level security;


  create table "public"."work_items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "work_category_id" bigint not null,
    "type" public.work_type,
    "title" text not null,
    "description" text
      );


alter table "public"."work_items" enable row level security;


  create table "public"."work_misc" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."work_misc" enable row level security;


  create table "public"."work_tasks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "deadline" date,
    "time_estimate" smallint,
    "contact_person_uuid" uuid,
    "max_participants" smallint default 1
      );


alter table "public"."work_tasks" enable row level security;

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX task_pkey ON public.work_tasks USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX work_assignments_pkey ON public.work_assignments USING btree (id);

CREATE UNIQUE INDEX work_categories_pkey ON public.work_categories USING btree (id);

CREATE UNIQUE INDEX work_items_pkey ON public.work_items USING btree (id);

CREATE UNIQUE INDEX work_misc_pkey ON public.work_misc USING btree (id);

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."work_assignments" add constraint "work_assignments_pkey" PRIMARY KEY using index "work_assignments_pkey";

alter table "public"."work_categories" add constraint "work_categories_pkey" PRIMARY KEY using index "work_categories_pkey";

alter table "public"."work_items" add constraint "work_items_pkey" PRIMARY KEY using index "work_items_pkey";

alter table "public"."work_misc" add constraint "work_misc_pkey" PRIMARY KEY using index "work_misc_pkey";

alter table "public"."work_tasks" add constraint "task_pkey" PRIMARY KEY using index "task_pkey";

alter table "public"."users" add constraint "users_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "users_role_id_fkey";

alter table "public"."users" add constraint "users_school_id_fkey" FOREIGN KEY (school_id) REFERENCES public.schools(id) not valid;

alter table "public"."users" validate constraint "users_school_id_fkey";

alter table "public"."users" add constraint "users_study_id_fkey" FOREIGN KEY (study_id) REFERENCES public.studies(id) not valid;

alter table "public"."users" validate constraint "users_study_id_fkey";

alter table "public"."work_assignments" add constraint "work_assignments_approved_by_uuid_fkey" FOREIGN KEY (approved_by_uuid) REFERENCES public.users(id) not valid;

alter table "public"."work_assignments" validate constraint "work_assignments_approved_by_uuid_fkey";

alter table "public"."work_assignments" add constraint "work_assignments_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES public.users(id) not valid;

alter table "public"."work_assignments" validate constraint "work_assignments_user_uuid_fkey";

alter table "public"."work_assignments" add constraint "work_assignments_work_id_fkey" FOREIGN KEY (work_id) REFERENCES public.work_items(id) not valid;

alter table "public"."work_assignments" validate constraint "work_assignments_work_id_fkey";

alter table "public"."work_items" add constraint "work_items_work_category_id_fkey" FOREIGN KEY (work_category_id) REFERENCES public.work_categories(id) not valid;

alter table "public"."work_items" validate constraint "work_items_work_category_id_fkey";

alter table "public"."work_misc" add constraint "work_misc_id_fkey" FOREIGN KEY (id) REFERENCES public.work_items(id) not valid;

alter table "public"."work_misc" validate constraint "work_misc_id_fkey";

alter table "public"."work_tasks" add constraint "work_tasks_contact_person_uuid_fkey" FOREIGN KEY (contact_person_uuid) REFERENCES public.users(id) not valid;

alter table "public"."work_tasks" validate constraint "work_tasks_contact_person_uuid_fkey";

alter table "public"."work_tasks" add constraint "work_tasks_id_fkey" FOREIGN KEY (id) REFERENCES public.work_items(id) not valid;

alter table "public"."work_tasks" validate constraint "work_tasks_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_admin_or_regisjef()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.users u
    join public.roles r on r.id = u.role_id
    where u.id = auth.uid()
      and r.name in ('Admin', 'Regisjef')
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin_or_romsjef()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.users u
    join public.roles r on r.id = u.role_id
    where u.id = auth.uid()
      and r.name in ('Admin', 'Romsjef')
  );
$function$
;

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "prisma";

grant insert on table "public"."roles" to "prisma";

grant references on table "public"."roles" to "prisma";

grant select on table "public"."roles" to "prisma";

grant trigger on table "public"."roles" to "prisma";

grant truncate on table "public"."roles" to "prisma";

grant update on table "public"."roles" to "prisma";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."schools" to "prisma";

grant insert on table "public"."schools" to "prisma";

grant references on table "public"."schools" to "prisma";

grant select on table "public"."schools" to "prisma";

grant trigger on table "public"."schools" to "prisma";

grant truncate on table "public"."schools" to "prisma";

grant update on table "public"."schools" to "prisma";

grant delete on table "public"."studies" to "prisma";

grant insert on table "public"."studies" to "prisma";

grant references on table "public"."studies" to "prisma";

grant select on table "public"."studies" to "prisma";

grant trigger on table "public"."studies" to "prisma";

grant truncate on table "public"."studies" to "prisma";

grant update on table "public"."studies" to "prisma";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "prisma";

grant insert on table "public"."users" to "prisma";

grant references on table "public"."users" to "prisma";

grant select on table "public"."users" to "prisma";

grant trigger on table "public"."users" to "prisma";

grant truncate on table "public"."users" to "prisma";

grant update on table "public"."users" to "prisma";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."work_assignments" to "anon";

grant insert on table "public"."work_assignments" to "anon";

grant references on table "public"."work_assignments" to "anon";

grant select on table "public"."work_assignments" to "anon";

grant trigger on table "public"."work_assignments" to "anon";

grant truncate on table "public"."work_assignments" to "anon";

grant update on table "public"."work_assignments" to "anon";

grant delete on table "public"."work_assignments" to "authenticated";

grant insert on table "public"."work_assignments" to "authenticated";

grant references on table "public"."work_assignments" to "authenticated";

grant select on table "public"."work_assignments" to "authenticated";

grant trigger on table "public"."work_assignments" to "authenticated";

grant truncate on table "public"."work_assignments" to "authenticated";

grant update on table "public"."work_assignments" to "authenticated";

grant delete on table "public"."work_assignments" to "prisma";

grant insert on table "public"."work_assignments" to "prisma";

grant references on table "public"."work_assignments" to "prisma";

grant select on table "public"."work_assignments" to "prisma";

grant trigger on table "public"."work_assignments" to "prisma";

grant truncate on table "public"."work_assignments" to "prisma";

grant update on table "public"."work_assignments" to "prisma";

grant delete on table "public"."work_assignments" to "service_role";

grant insert on table "public"."work_assignments" to "service_role";

grant references on table "public"."work_assignments" to "service_role";

grant select on table "public"."work_assignments" to "service_role";

grant trigger on table "public"."work_assignments" to "service_role";

grant truncate on table "public"."work_assignments" to "service_role";

grant update on table "public"."work_assignments" to "service_role";

grant delete on table "public"."work_categories" to "anon";

grant insert on table "public"."work_categories" to "anon";

grant references on table "public"."work_categories" to "anon";

grant select on table "public"."work_categories" to "anon";

grant trigger on table "public"."work_categories" to "anon";

grant truncate on table "public"."work_categories" to "anon";

grant update on table "public"."work_categories" to "anon";

grant delete on table "public"."work_categories" to "authenticated";

grant insert on table "public"."work_categories" to "authenticated";

grant references on table "public"."work_categories" to "authenticated";

grant select on table "public"."work_categories" to "authenticated";

grant trigger on table "public"."work_categories" to "authenticated";

grant truncate on table "public"."work_categories" to "authenticated";

grant update on table "public"."work_categories" to "authenticated";

grant delete on table "public"."work_categories" to "prisma";

grant insert on table "public"."work_categories" to "prisma";

grant references on table "public"."work_categories" to "prisma";

grant select on table "public"."work_categories" to "prisma";

grant trigger on table "public"."work_categories" to "prisma";

grant truncate on table "public"."work_categories" to "prisma";

grant update on table "public"."work_categories" to "prisma";

grant delete on table "public"."work_categories" to "service_role";

grant insert on table "public"."work_categories" to "service_role";

grant references on table "public"."work_categories" to "service_role";

grant select on table "public"."work_categories" to "service_role";

grant trigger on table "public"."work_categories" to "service_role";

grant truncate on table "public"."work_categories" to "service_role";

grant update on table "public"."work_categories" to "service_role";

grant delete on table "public"."work_items" to "anon";

grant insert on table "public"."work_items" to "anon";

grant references on table "public"."work_items" to "anon";

grant select on table "public"."work_items" to "anon";

grant trigger on table "public"."work_items" to "anon";

grant truncate on table "public"."work_items" to "anon";

grant update on table "public"."work_items" to "anon";

grant delete on table "public"."work_items" to "authenticated";

grant insert on table "public"."work_items" to "authenticated";

grant references on table "public"."work_items" to "authenticated";

grant select on table "public"."work_items" to "authenticated";

grant trigger on table "public"."work_items" to "authenticated";

grant truncate on table "public"."work_items" to "authenticated";

grant update on table "public"."work_items" to "authenticated";

grant delete on table "public"."work_items" to "prisma";

grant insert on table "public"."work_items" to "prisma";

grant references on table "public"."work_items" to "prisma";

grant select on table "public"."work_items" to "prisma";

grant trigger on table "public"."work_items" to "prisma";

grant truncate on table "public"."work_items" to "prisma";

grant update on table "public"."work_items" to "prisma";

grant delete on table "public"."work_items" to "service_role";

grant insert on table "public"."work_items" to "service_role";

grant references on table "public"."work_items" to "service_role";

grant select on table "public"."work_items" to "service_role";

grant trigger on table "public"."work_items" to "service_role";

grant truncate on table "public"."work_items" to "service_role";

grant update on table "public"."work_items" to "service_role";

grant delete on table "public"."work_misc" to "anon";

grant insert on table "public"."work_misc" to "anon";

grant references on table "public"."work_misc" to "anon";

grant select on table "public"."work_misc" to "anon";

grant trigger on table "public"."work_misc" to "anon";

grant truncate on table "public"."work_misc" to "anon";

grant update on table "public"."work_misc" to "anon";

grant delete on table "public"."work_misc" to "authenticated";

grant insert on table "public"."work_misc" to "authenticated";

grant references on table "public"."work_misc" to "authenticated";

grant select on table "public"."work_misc" to "authenticated";

grant trigger on table "public"."work_misc" to "authenticated";

grant truncate on table "public"."work_misc" to "authenticated";

grant update on table "public"."work_misc" to "authenticated";

grant delete on table "public"."work_misc" to "prisma";

grant insert on table "public"."work_misc" to "prisma";

grant references on table "public"."work_misc" to "prisma";

grant select on table "public"."work_misc" to "prisma";

grant trigger on table "public"."work_misc" to "prisma";

grant truncate on table "public"."work_misc" to "prisma";

grant update on table "public"."work_misc" to "prisma";

grant delete on table "public"."work_misc" to "service_role";

grant insert on table "public"."work_misc" to "service_role";

grant references on table "public"."work_misc" to "service_role";

grant select on table "public"."work_misc" to "service_role";

grant trigger on table "public"."work_misc" to "service_role";

grant truncate on table "public"."work_misc" to "service_role";

grant update on table "public"."work_misc" to "service_role";

grant delete on table "public"."work_tasks" to "anon";

grant insert on table "public"."work_tasks" to "anon";

grant references on table "public"."work_tasks" to "anon";

grant select on table "public"."work_tasks" to "anon";

grant trigger on table "public"."work_tasks" to "anon";

grant truncate on table "public"."work_tasks" to "anon";

grant update on table "public"."work_tasks" to "anon";

grant delete on table "public"."work_tasks" to "authenticated";

grant insert on table "public"."work_tasks" to "authenticated";

grant references on table "public"."work_tasks" to "authenticated";

grant select on table "public"."work_tasks" to "authenticated";

grant trigger on table "public"."work_tasks" to "authenticated";

grant truncate on table "public"."work_tasks" to "authenticated";

grant update on table "public"."work_tasks" to "authenticated";

grant delete on table "public"."work_tasks" to "prisma";

grant insert on table "public"."work_tasks" to "prisma";

grant references on table "public"."work_tasks" to "prisma";

grant select on table "public"."work_tasks" to "prisma";

grant trigger on table "public"."work_tasks" to "prisma";

grant truncate on table "public"."work_tasks" to "prisma";

grant update on table "public"."work_tasks" to "prisma";

grant delete on table "public"."work_tasks" to "service_role";

grant insert on table "public"."work_tasks" to "service_role";

grant references on table "public"."work_tasks" to "service_role";

grant select on table "public"."work_tasks" to "service_role";

grant trigger on table "public"."work_tasks" to "service_role";

grant truncate on table "public"."work_tasks" to "service_role";

grant update on table "public"."work_tasks" to "service_role";


  create policy "Authenticated users can read roles"
  on "public"."roles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admins can update any user"
  on "public"."users"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text, 'Romsjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text, 'Romsjef'::text]))))));



  create policy "Authenticated users can read all users"
  on "public"."users"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can delete non-admin users"
  on "public"."users"
  as permissive
  for delete
  to authenticated
using (((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))) AND (NOT (EXISTS ( SELECT 1
   FROM public.roles r
  WHERE ((r.id = users.role_id) AND (r.name = 'Admin'::text)))))));



  create policy "Users can update own profile"
  on "public"."users"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Authenticated users can read assignments"
  on "public"."work_assignments"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can delete any assignment"
  on "public"."work_assignments"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can insert any assignment"
  on "public"."work_assignments"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can update any assignment"
  on "public"."work_assignments"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Users can delete own assignments"
  on "public"."work_assignments"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_uuid));



  create policy "Users can insert own assignments"
  on "public"."work_assignments"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_uuid));



  create policy "Authenticated users can read categories"
  on "public"."work_categories"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can insert categories"
  on "public"."work_categories"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can update categories"
  on "public"."work_categories"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Authenticated users can insert work items"
  on "public"."work_items"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Authenticated users can read work items"
  on "public"."work_items"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can delete work items"
  on "public"."work_items"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can update work items"
  on "public"."work_items"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Authenticated users can read work_misc"
  on "public"."work_misc"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can delete work_misc"
  on "public"."work_misc"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can insert work_misc"
  on "public"."work_misc"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can update work_misc"
  on "public"."work_misc"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Authenticated users can read tasks"
  on "public"."work_tasks"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Managers can delete tasks"
  on "public"."work_tasks"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can insert tasks"
  on "public"."work_tasks"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));



  create policy "Managers can update tasks"
  on "public"."work_tasks"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))))
with check ((EXISTS ( SELECT 1
   FROM (public.users u
     JOIN public.roles r ON ((u.role_id = r.id)))
  WHERE ((u.id = auth.uid()) AND (r.name = ANY (ARRAY['Admin'::text, 'Data'::text, 'Regisjef'::text]))))));


drop trigger if exists "objects_delete_delete_prefix" on "storage"."objects";

drop trigger if exists "objects_insert_create_prefix" on "storage"."objects";

drop trigger if exists "objects_update_create_prefix" on "storage"."objects";

drop trigger if exists "prefixes_create_hierarchy" on "storage"."prefixes";

drop trigger if exists "prefixes_delete_hierarchy" on "storage"."prefixes";


  create policy "users can delete own images"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'Bilder'::text) AND (name ~~ (auth.uid() || '/%'::text))));



  create policy "users can read own images"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'Bilder'::text) AND (name ~~ (auth.uid() || '/%'::text))));



  create policy "users can upload own images"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'Bilder'::text) AND (name ~~ (auth.uid() || '/%'::text))));


do $$
begin
  if to_regprocedure('storage.protect_delete()') is not null then
    drop trigger if exists protect_buckets_delete on storage.buckets;
    create trigger protect_buckets_delete
      before delete on storage.buckets
      for each statement
      execute function storage.protect_delete();

    drop trigger if exists protect_objects_delete on storage.objects;
    create trigger protect_objects_delete
      before delete on storage.objects
      for each statement
      execute function storage.protect_delete();
  end if;
end
$$;
